# Output
#markdown: redcarpet
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
relative_permalinks: false
safe: true
future: false
sass:
  style: compressed
  sass_dir: _sass

repository: https://vashman.github.io/web_media

# Directory Structure
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
baseurl: /web_media
collections:
  media:
    output: true

# site variables
default_layout: css/layout/vintage.css
default_theme: css/theme/vintage.css

defaults:
  - scope:
      path: ""
      type: "media"
    values:
      layout: media

# Local build variables
# Root paths relative to differnt sub-directories
post_root_url: ../../
media_root_url: ../
