# Output
#markdown: redcarpet
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: pygments
relative_permalinks: false
safe: true
future: false
sass:
  style: compressed
  sass_dir: _sass

repository: https://vashman.github.io/web_media

# Directory Structure
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
baseurl: /web_media
collections:  null

# site variables
default_layout: css/layout/vintage.css
default_theme: css/theme/vintage.css
